server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;
    server_name _;

    add_header Cache-Control "no-cache, no-store, must-revalidate";
    add_header Pragma "no-cache";
    add_header Expires "0";

    location / {
        try_files $uri $uri/ /index.html;
    }
}
